language: python

python:
      - "2.7"
      - "3.4"
      - "3.5"
      - "3.6"
      - "3.7"
      - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
    - "pip install --editable .[dev]"
    - "pip install python-coveralls"
script:
    - "pytest -v  --cov-report= --cov=orbit_predictor tests/"
after_script:
    - "flake8 orbit_predictor"

# report coverage to coveralls.io
after_success:
    - coveralls

cache:
  apt: true
  pip: true
